// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Install(arg1) {
  return window['go']['backend']['Actions']['Install'](arg1);
}

export function Other(arg1, arg2) {
  return window['go']['backend']['Actions']['Other'](arg1, arg2);
}

export function Repair(arg1) {
  return window['go']['backend']['Actions']['Repair'](arg1);
}

export function SetContext(arg1) {
  return window['go']['backend']['Actions']['SetContext'](arg1);
}

export function Uninstall(arg1) {
  return window['go']['backend']['Actions']['Uninstall'](arg1);
}
