// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {discord} from '../models';
import {context} from '../models';

export function Install(arg1:Array<string>):Promise<void>;

export function Other(arg1:discord.DiscordInstall,arg2:discord.DiscordChannel):Promise<void>;

export function Repair(arg1:Array<string>):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function Uninstall(arg1:Array<string>):Promise<void>;
