// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetModules() {
  return window['go']['backend']['Backend']['GetModules']();
}

export function GetPlatform() {
  return window['go']['backend']['Backend']['GetPlatform']();
}

export function KillProcess(arg1, arg2) {
  return window['go']['backend']['Backend']['KillProcess'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['backend']['Backend']['SetContext'](arg1);
}
