// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function GetDiscordPath(arg1:string):Promise<string>;

export function GetModules():Promise<Array<any>>;

export function LogTest(arg1:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;
