// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDiscordPath(arg1) {
  return window['go']['backend']['Backend']['GetDiscordPath'](arg1);
}

export function GetModules() {
  return window['go']['backend']['Backend']['GetModules']();
}

export function LogTest(arg1) {
  return window['go']['backend']['Backend']['LogTest'](arg1);
}

export function SetContext(arg1) {
  return window['go']['backend']['Backend']['SetContext'](arg1);
}
