# https://taskfile.dev

# TODO: Expand on this using Wails v3 as a reference

version: '3'

env:
  PKG_CONFIG_PATH: '{{ if contains .WSL_DISTRO_NAME "Fedora" }}/usr/lib64/pkgconfig:/usr/share/pkgconfig{{ end }}'

vars:
  BINARY_NAME: BetterDiscord-Installer

tasks:
  default:
    deps: [dev]

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf build
      - rm -rf frontend/build
      - rm -rf frontend/node_modules

  frontend:install:
    desc: Install frontend dependencies
    dir: frontend
    sources:
      - package.json
      - bun.lock
    cmds:
      - bun install

  frontend:build:
    desc: Build the Sveltekit frontend
    deps: [frontend:install]
    dir: frontend
    sources:
      - "frontend/src/**/*"
      - "frontend/*.config.*"
    generates:
      - "frontend/build/**/*"
      - "frontend/.svelte-kit/**/*"
    cmds:
      - bun run build

  frontend:dev:
    desc: Start the Sveltekit development server
    deps: [frontend:install]
    dir: frontend
    cmds:
      - bun run dev

  dev:
    desc: Start development server
    deps: [frontend:build]
    vars:
      REVISION: "$(git rev-parse --short HEAD)"
    cmds:
      # -s skips the frontend build step since it is a dep of the dev task
      - wails dev -s -ldflags="-X main.version={{.REVISION}}"

  build:
    desc: Build the application
    deps: [frontend:build]
    vars:
      VERSION: "$(git describe --tags --abbrev=0)"
    sources:
      - "frontend/src/**/*"
      - "frontend/*.config.*"
      - "**/*.go"
    generates:
      - "build/{{.BINARY_NAME}}*"
    cmds:
      # -s skips the frontend build step since it is a dep of the build task
      - wails build -s -ldflags="-X main.version={{.VERSION}}"

  # TODO: Rewrite task in tandem with github actions
  build-all:
    desc: Build for all platforms
    deps: [frontend:build]
    cmds:
      # -s skips the frontend build step since it is a dep of the build task
      - wails build -s -platform windows/amd64 -o {{.BINARY_NAME}}-windows-amd64.exe
      - wails build -s -platform windows/arm64 -o {{.BINARY_NAME}}-windows-arm64.exe
      - wails build -s -platform darwin/universal -o {{.BINARY_NAME}}-darwin-universal
      - wails build -s -platform linux/amd64 -o {{.BINARY_NAME}}-linux-amd64
      - wails build -s -platform linux/arm64 -o {{.BINARY_NAME}}-linux-arm64

  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  lint:
    desc: Run linters
    cmds:
      - task: lint:frontend
      - task: lint:go

  lint:go:
    desc: Run Go linters
    cmds:
      - golangci-lint run

  lint:frontend:
    desc: Run frontend linters
    dir: frontend
    cmds:
      - bun run lint

  # Requires version to be set in the format vX.Y.Z
  release:*:
    desc: Create a new release
    deps: [test]
    vars:
      NEW_VERSION: "{{index .MATCH 0}}"
    cmds:
      - git tag {{.NEW_VERSION}}
      - task: generate-changelog
        vars: { VERSION: "{{.NEW_VERSION}}" }
      - task: build-all
        vars: { VERSION: "{{.NEW_VERSION}}" }
      - git push origin {{.NEW_VERSION}}

  generate-changelog:
    desc: Generate changelog since last release
    silent: true
    vars:
      VERSION: "$(git describe --tags --abbrev=0)"
    cmds:
      - |
        echo "## [{{.VERSION}}] - $(date +%Y-%m-%d)" > CHANGELOG.md
        echo "" >> CHANGELOG.md
        git log $(git describe --tags --abbrev=0 HEAD^)..HEAD --pretty=format:'- %s' >> CHANGELOG.md
