blank_issues_enabled: false
contact_links:
  - name: BetterDiscord Community (Discord)
    url: https://betterdiscord.app/invite
    about: For install help, usage questions, and general support, please ask in our Discord community first.
