// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function BrowseForDiscord(arg1:string):Promise<string>;

export function ConfirmAction(arg1:string,arg2:string):Promise<string>;

export function GetDiscordPath(arg1:string):Promise<string>;

export function Install(arg1:Array<string>):Promise<void>;

export function Repair(arg1:Array<string>):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function ShowNotice(arg1:string,arg2:string,arg3:string):Promise<string>;

export function Uninstall(arg1:Array<string>):Promise<void>;

export function Write(arg1:Array<number>):Promise<number>;
