// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseForDiscord(arg1) {
  return window['go']['api']['Controller']['BrowseForDiscord'](arg1);
}

export function ConfirmAction(arg1, arg2) {
  return window['go']['api']['Controller']['ConfirmAction'](arg1, arg2);
}

export function GetDiscordPath(arg1) {
  return window['go']['api']['Controller']['GetDiscordPath'](arg1);
}

export function Install(arg1) {
  return window['go']['api']['Controller']['Install'](arg1);
}

export function Repair(arg1) {
  return window['go']['api']['Controller']['Repair'](arg1);
}

export function SetContext(arg1) {
  return window['go']['api']['Controller']['SetContext'](arg1);
}

export function ShowNotice(arg1, arg2, arg3) {
  return window['go']['api']['Controller']['ShowNotice'](arg1, arg2, arg3);
}

export function Uninstall(arg1) {
  return window['go']['api']['Controller']['Uninstall'](arg1);
}

export function Write(arg1) {
  return window['go']['api']['Controller']['Write'](arg1);
}
