// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function SetContext(arg1) {
  return window['go']['main']['App']['SetContext'](arg1);
}

export function Write(arg1) {
  return window['go']['main']['App']['Write'](arg1);
}
